import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import InputForm from '@/components/InputForm'
import Table from '@/components/Table'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
 // console.log(data)
  const [visible, setVisible] = useState(true)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1 className="flex items-center justify-center">Employee Management</h1>
     <button name="change" className='border-2 border-red-500 cursor-pointer' onClick={()=>{setVisible(!visible)}}>Change</button>
      {visible?<InputForm/>:<></>}
     
     <div>
     <Table data={data}/>
     </div>
 
    </>
  )
}
export const getServerSideProps =async()=>{
  const response = await fetch("http://localhost:3000/api/users")
  const data = await response.json()
   return {
    props:{
      data
       }
   }
} 
 